"""
Export this project's analysis output as a Jianying draft folder.

The exporter intentionally creates a new draft directory. It does not overwrite
existing encrypted drafts generated by newer Jianying versions.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any


DEFAULT_DRAFT_ROOT = Path(
    "/Users/apple1/Movies/JianyingPro/User Data/Projects/com.lveditor.draft"
)
DEFAULT_TEMPLATE_DIR = Path(
    "/Users/apple1/AI_Code/CapCutAPI/src/service/template_jianying"
)


VIDEO_EXTENSIONS = {".mp4", ".mov", ".m4v", ".avi", ".mkv", ".webm"}
AUDIO_EXTENSIONS = {".mp3", ".wav", ".m4a", ".aac", ".mov"}


def new_id() -> str:
    return str(uuid.uuid4()).upper()


def to_us(seconds: float) -> int:
    return max(0, int(round(float(seconds) * 1_000_000)))


def now_us() -> int:
    return int(datetime.now().timestamp() * 1_000_000)


def safe_draft_name(name: str) -> str:
    name = re.sub(r"[/:\\\0]", "_", name).strip()
    name = re.sub(r"\s+", " ", name)
    return name[:80] or f"chai_export_{datetime.now():%Y%m%d_%H%M%S}"


def run_json(cmd: list[str]) -> dict[str, Any]:
    result = subprocess.run(cmd, check=True, capture_output=True, text=True)
    return json.loads(result.stdout)


def probe_media(path: Path) -> dict[str, Any]:
    data = run_json(
        [
            "ffprobe",
            "-v",
            "error",
            "-show_streams",
            "-show_format",
            "-print_format",
            "json",
            str(path),
        ]
    )
    streams = data.get("streams", [])
    video_stream = next((s for s in streams if s.get("codec_type") == "video"), None)
    audio_stream = next((s for s in streams if s.get("codec_type") == "audio"), None)

    duration = None
    for source in (video_stream, audio_stream, data.get("format", {})):
        if source and source.get("duration") not in (None, "N/A"):
            duration = float(source["duration"])
            break

    return {
        "duration": to_us(duration or 0),
        "width": int(video_stream.get("width", 0)) if video_stream else 0,
        "height": int(video_stream.get("height", 0)) if video_stream else 0,
        "has_audio": audio_stream is not None,
    }


def load_json(path: Path, default: Any = None) -> Any:
    if not path.exists():
        return default
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def dump_json(path: Path, data: Any, *, pretty: bool = True) -> None:
    with path.open("w", encoding="utf-8") as f:
        if pretty:
            json.dump(data, f, ensure_ascii=False, indent=4)
        else:
            json.dump(data, f, ensure_ascii=False, separators=(",", ":"))


def copy_template(template_dir: Path, draft_dir: Path) -> None:
    if not template_dir.exists():
        raise FileNotFoundError(f"Template directory not found: {template_dir}")
    if draft_dir.exists():
        raise FileExistsError(f"Draft already exists: {draft_dir}")
    shutil.copytree(template_dir, draft_dir)
    for subdir in ("video", "audio", "Resources", "common_attachment", "Timelines"):
        (draft_dir / subdir).mkdir(exist_ok=True)


def discover_output(output_dir: Path) -> tuple[dict[str, Any], list[Path], Path | None, list[dict[str, Any]]]:
    if not output_dir.exists():
        raise FileNotFoundError(f"Output directory not found: {output_dir}")

    report = load_json(output_dir / "report.json", {})
    scenes_dir = output_dir / "scenes"
    scene_files = sorted(
        p for p in scenes_dir.glob("*") if p.suffix.lower() in VIDEO_EXTENSIONS
    )
    if not scene_files and (output_dir / "video_no_subtitles.mp4").exists():
        scene_files = [output_dir / "video_no_subtitles.mp4"]
    if not scene_files:
        raise FileNotFoundError(f"No scene videos found in: {scenes_dir}")

    audio_path = output_dir / "audio.mp3"
    if not audio_path.exists():
        audio_candidates = sorted(
            p for p in output_dir.glob("*") if p.suffix.lower() in AUDIO_EXTENSIONS
        )
        audio_path = audio_candidates[0] if audio_candidates else None

    transcript = load_json(output_dir / "transcript_detailed.json", None)
    if transcript is None:
        transcript = report.get("transcript_segments", [])

    return report, scene_files, audio_path, transcript or []


def make_speed(speed_id: str, speed: float = 1.0) -> dict[str, Any]:
    return {
        "curve_speed": None,
        "id": speed_id,
        "mode": 0,
        "speed": speed,
        "type": "speed",
    }


def make_video_material(
    material_id: str,
    path: str,
    name: str,
    duration: int,
    width: int,
    height: int,
) -> dict[str, Any]:
    return {
        "audio_fade": None,
        "category_id": "",
        "category_name": "local",
        "check_flag": 63487,
        "crop": {
            "upper_left_x": 0.0,
            "upper_left_y": 0.0,
            "upper_right_x": 1.0,
            "upper_right_y": 0.0,
            "lower_left_x": 0.0,
            "lower_left_y": 1.0,
            "lower_right_x": 1.0,
            "lower_right_y": 1.0,
        },
        "crop_ratio": "free",
        "crop_scale": 1.0,
        "duration": duration,
        "height": height,
        "id": material_id,
        "local_material_id": "",
        "material_id": material_id,
        "material_name": name,
        "media_path": path,
        "path": path,
        "remote_url": None,
        "type": "video",
        "width": width,
    }


def make_audio_material(material_id: str, path: str, name: str, duration: int) -> dict[str, Any]:
    return {
        "app_id": 0,
        "category_id": "",
        "category_name": "local",
        "check_flag": 1,
        "copyright_limit_type": "none",
        "duration": duration,
        "effect_id": "",
        "formula_id": "",
        "id": material_id,
        "intensifies_path": "",
        "is_ai_clone_tone": False,
        "is_text_edit_overdub": False,
        "is_ugc": False,
        "local_material_id": material_id,
        "music_id": material_id,
        "name": name,
        "path": path,
        "remote_url": None,
        "query": "",
        "request_id": "",
        "resource_id": "",
        "search_id": "",
        "source_from": "",
        "source_platform": 0,
        "team_id": "",
        "text_id": "",
        "tone_category_id": "",
        "tone_category_name": "",
        "tone_effect_id": "",
        "tone_effect_name": "",
        "tone_platform": "",
        "tone_second_category_id": "",
        "tone_second_category_name": "",
        "tone_speaker": "",
        "tone_type": "",
        "type": "extract_music",
        "video_id": "",
        "wave_points": [],
    }


def make_text_material(material_id: str, text: str, *, fixed_width: int) -> dict[str, Any]:
    text = text.strip()
    content = {
        "styles": [
            {
                "fill": {
                    "alpha": 1.0,
                    "content": {
                        "render_type": "solid",
                        "solid": {"alpha": 1.0, "color": [1.0, 1.0, 1.0]},
                    },
                },
                "range": [0, len(text)],
                "size": 5.0,
                "bold": False,
                "italic": False,
                "underline": False,
                "strokes": [
                    {
                        "alpha": 1.0,
                        "content": {
                            "render_type": "solid",
                            "solid": {"alpha": 1.0, "color": [0.0, 0.0, 0.0]},
                        },
                        "width": 0.08,
                    }
                ],
            }
        ],
        "text": text,
    }
    return {
        "id": material_id,
        "content": json.dumps(content, ensure_ascii=False),
        "type": "text",
        "typesetting": 0,
        "alignment": 1,
        "letter_spacing": 0,
        "line_spacing": 0.02,
        "line_feed": 1,
        "line_max_width": 0.82,
        "force_apply_line_max_width": False,
        "check_flag": 15,
        "fixed_width": fixed_width,
        "fixed_height": -1,
        "font_category_id": "",
        "font_category_name": "",
        "font_id": "",
        "font_name": "",
        "font_path": "",
        "font_resource_id": "",
        "font_size": 5.0,
        "font_source_platform": 0,
        "font_team_id": "",
        "font_title": "none",
        "font_url": "",
        "fonts": [],
        "text_color": "#ffffff",
        "text_size": 30,
        "border_color": "#000000",
        "border_alpha": 1,
        "border_width": 0.08,
        "background_alpha": 1,
        "background_color": "",
        "background_style": 0,
        "background_height": 0.14,
        "background_width": 0.14,
        "background_round_radius": 0,
        "background_horizontal_offset": 0,
        "background_vertical_offset": 0,
    }


def base_segment(
    segment_id: str,
    material_id: str,
    start: int,
    duration: int,
    *,
    render_index: int,
    volume: float,
    speed_id: str | None,
    source_timerange: dict[str, int] | None,
) -> dict[str, Any]:
    refs = [speed_id] if speed_id else []
    return {
        "enable_adjust": True,
        "enable_color_correct_adjust": False,
        "enable_color_curves": True,
        "enable_color_match_adjust": False,
        "enable_color_wheels": True,
        "enable_lut": True,
        "enable_smart_color_adjust": False,
        "last_nonzero_volume": 1.0,
        "reverse": False,
        "track_attribute": 0,
        "track_render_index": 0,
        "visible": True,
        "id": segment_id,
        "material_id": material_id,
        "target_timerange": {"start": start, "duration": duration},
        "source_timerange": source_timerange,
        "speed": 1.0,
        "volume": volume,
        "extra_material_refs": refs,
        "common_keyframes": [],
        "keyframe_refs": [],
        "render_index": render_index,
    }


def make_visual_segment(
    segment_id: str,
    material_id: str,
    start: int,
    duration: int,
    *,
    render_index: int,
    volume: float,
    speed_id: str | None,
    source_timerange: dict[str, int] | None,
    transform_y: float = 0.0,
) -> dict[str, Any]:
    seg = base_segment(
        segment_id,
        material_id,
        start,
        duration,
        render_index=render_index,
        volume=volume,
        speed_id=speed_id,
        source_timerange=source_timerange,
    )
    seg.update(
        {
            "clip": {
                "alpha": 1.0,
                "flip": {"horizontal": False, "vertical": False},
                "rotation": 0.0,
                "scale": {"x": 1.0, "y": 1.0},
                "transform": {"x": 0.0, "y": transform_y},
            },
            "uniform_scale": {"on": True, "value": 1.0},
            "hdr_settings": {"intensity": 1.0, "mode": 1, "nits": 1000},
        }
    )
    return seg


def make_audio_segment(
    segment_id: str,
    material_id: str,
    start: int,
    duration: int,
    speed_id: str,
) -> dict[str, Any]:
    seg = base_segment(
        segment_id,
        material_id,
        start,
        duration,
        render_index=0,
        volume=1.0,
        speed_id=speed_id,
        source_timerange={"start": 0, "duration": duration},
    )
    seg.update({"clip": None, "hdr_settings": None})
    return seg


def make_track(track_type: str, name: str, segments: list[dict[str, Any]], *, flag: int = 0) -> dict[str, Any]:
    return {
        "attribute": 0,
        "flag": flag,
        "id": new_id(),
        "is_default_name": False,
        "name": name,
        "segments": segments,
        "type": track_type,
    }


def update_meta(draft_dir: Path, draft_id: str, draft_name: str, duration: int) -> None:
    meta_path = draft_dir / "draft_meta_info.json"
    meta = load_json(meta_path, {})
    timestamp = now_us()
    meta.update(
        {
            "draft_cover": "draft_cover.jpg",
            "draft_fold_path": str(draft_dir),
            "draft_id": draft_id,
            "draft_name": draft_name,
            "draft_root_path": str(draft_dir.parent),
            "tm_draft_create": timestamp,
            "tm_draft_modified": timestamp,
            "tm_duration": duration,
        }
    )
    dump_json(meta_path, meta, pretty=True)


def write_timeline_files(draft_dir: Path, draft_id: str, draft_content: dict[str, Any]) -> None:
    timelines_dir = draft_dir / "Timelines"
    timeline_dir = timelines_dir / draft_id
    timeline_dir.mkdir(parents=True, exist_ok=True)
    timestamp = now_us()
    project = {
        "config": {
            "color_space": -1,
            "render_index_track_mode_on": True,
            "use_float_render": False,
        },
        "create_time": timestamp,
        "id": draft_id,
        "main_timeline_id": draft_id,
        "timelines": [
            {
                "create_time": timestamp,
                "id": draft_id,
                "is_marked_delete": False,
                "name": "",
                "update_time": timestamp,
            }
        ],
        "update_time": timestamp,
        "version": 0,
    }
    dump_json(timelines_dir / "project.json", project, pretty=False)
    dump_json(timeline_dir / "draft_info.json", draft_content, pretty=True)


def try_generate_cover(draft_dir: Path, first_video: Path) -> None:
    cover = draft_dir / "draft_cover.jpg"
    try:
        subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-v",
                "error",
                "-i",
                str(first_video),
                "-frames:v",
                "1",
                str(cover),
            ],
            check=True,
        )
    except Exception:
        # The template already contains a fallback cover in most cases.
        pass


def build_draft(
    output_dir: Path,
    draft_root: Path,
    template_dir: Path,
    draft_name: str | None = None,
) -> Path:
    report, scene_files, audio_path, transcript = discover_output(output_dir)
    title = report.get("video_name") or output_dir.name
    draft_name = safe_draft_name(draft_name or f"chai_{title}_{datetime.now():%H%M%S}")
    draft_dir = draft_root / draft_name

    copy_template(template_dir, draft_dir)

    draft_id = new_id()
    video_dir = draft_dir / "video"
    audio_dir = draft_dir / "audio"

    base_info = load_json(template_dir / "draft_info.json")
    materials = {key: [] for key in base_info.get("materials", {}).keys()}
    for extra_key in ("common_mask", "audio_pannings", "audio_pitch_shifts", "hsl_curves",
                      "manual_beautys", "placeholder_infos", "video_radius",
                      "video_shadows", "video_strokes"):
        materials.setdefault(extra_key, [])

    video_segments: list[dict[str, Any]] = []
    timeline_pos = 0
    canvas_width = 1920
    canvas_height = 1080

    report_scenes = report.get("scenes") or []
    for index, src in enumerate(scene_files, start=1):
        probe = probe_media(src)
        scene_duration = 0
        if index <= len(report_scenes):
            scene_duration = to_us(report_scenes[index - 1].get("duration", 0))
        duration = scene_duration or probe["duration"]
        if duration <= 0:
            continue

        if probe["width"] and probe["height"]:
            canvas_width, canvas_height = probe["width"], probe["height"]

        target_name = f"Scene-{index:03d}{src.suffix.lower()}"
        target_path = video_dir / target_name
        shutil.copy2(src, target_path)

        material_id = new_id()
        speed_id = new_id()
        materials["videos"].append(
            make_video_material(
                material_id,
                str(target_path),
                target_name,
                duration,
                probe["width"] or canvas_width,
                probe["height"] or canvas_height,
            )
        )
        materials["speeds"].append(make_speed(speed_id))
        video_segments.append(
            make_visual_segment(
                new_id(),
                material_id,
                timeline_pos,
                duration,
                render_index=0,
                volume=0.0,
                speed_id=speed_id,
                source_timerange={"start": 0, "duration": duration},
            )
        )
        timeline_pos += duration

    audio_segments: list[dict[str, Any]] = []
    if audio_path and audio_path.exists():
        audio_probe = probe_media(audio_path)
        audio_duration = min(audio_probe["duration"] or timeline_pos, timeline_pos)
        target_audio_name = f"audio{audio_path.suffix.lower()}"
        target_audio_path = audio_dir / target_audio_name
        shutil.copy2(audio_path, target_audio_path)

        audio_material_id = new_id()
        audio_speed_id = new_id()
        materials["audios"].append(
            make_audio_material(
                audio_material_id,
                str(target_audio_path),
                target_audio_name,
                audio_duration,
            )
        )
        materials["speeds"].append(make_speed(audio_speed_id))
        audio_segments.append(
            make_audio_segment(new_id(), audio_material_id, 0, audio_duration, audio_speed_id)
        )

    text_segments: list[dict[str, Any]] = []
    fixed_width = int(canvas_width * 0.7) if canvas_width >= canvas_height else int(canvas_width * 0.82)
    for item in transcript:
        text = str(item.get("text", "")).strip()
        if not text:
            continue
        start = to_us(item.get("start", 0))
        end = to_us(item.get("end", 0))
        duration = max(0, end - start)
        if duration <= 0 or start >= timeline_pos:
            continue
        duration = min(duration, timeline_pos - start)

        material_id = new_id()
        materials["texts"].append(make_text_material(material_id, text, fixed_width=fixed_width))
        text_segments.append(
            make_visual_segment(
                new_id(),
                material_id,
                start,
                duration,
                render_index=15000,
                volume=1.0,
                speed_id=None,
                source_timerange=None,
                transform_y=-0.78,
            )
        )

    tracks = [make_track("video", "主视频", video_segments)]
    if audio_segments:
        tracks.append(make_track("audio", "音频", audio_segments))
    if text_segments:
        tracks.append(make_track("text", "字幕", text_segments))

    timestamp = now_us()
    base_info.update(
        {
            "id": draft_id,
            "name": draft_name,
            "duration": timeline_pos,
            "fps": 30.0,
            "canvas_config": {
                "height": canvas_height,
                "ratio": "original",
                "width": canvas_width,
            },
            "create_time": timestamp,
            "update_time": timestamp,
            "materials": materials,
            "tracks": tracks,
            "static_cover_image_path": "draft_cover.jpg",
        }
    )
    platform = {
        "app_id": 3704,
        "app_source": "lv",
        "app_version": "5.9.0",
        "device_id": "",
        "hard_disk_id": "",
        "mac_address": "",
        "os": "mac",
        "os_version": "",
    }
    base_info["platform"] = platform
    base_info["last_modified_platform"] = platform

    for name in ("draft_info.json", "draft_info.json.bak", "template.tmp", "template-2.tmp", "template.json.bak"):
        dump_json(draft_dir / name, base_info, pretty=True)

    update_meta(draft_dir, draft_id, draft_name, timeline_pos)
    write_timeline_files(draft_dir, draft_id, base_info)
    try_generate_cover(draft_dir, video_dir / f"Scene-001{scene_files[0].suffix.lower()}")

    return draft_dir


def create_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Export analysis output to a Jianying draft folder.")
    parser.add_argument("output_dir", help="Analysis output directory containing report.json/scenes/audio.")
    parser.add_argument("--draft-root", default=str(DEFAULT_DRAFT_ROOT), help="Jianying draft root directory.")
    parser.add_argument("--template-dir", default=str(DEFAULT_TEMPLATE_DIR), help="Plain Jianying draft template directory.")
    parser.add_argument("--draft-name", help="New draft folder name. Defaults to a title-based name.")
    return parser


def main() -> None:
    args = create_parser().parse_args()
    draft_dir = build_draft(
        Path(args.output_dir).expanduser().resolve(),
        Path(args.draft_root).expanduser(),
        Path(args.template_dir).expanduser(),
        args.draft_name,
    )
    print(draft_dir)


if __name__ == "__main__":
    main()
